[project]
name = "cc-tmpl.py"
version = "0.7.2"
description = "An opinioned python template based on cookiecutter"
readme = "README.md"
license = "MIT"
authors = [
    {name = "Chuan-Heng Hsiao", email = "hsiao.chuanheng@gmail.com"},
]
requires-python = ">=3.10"
dependencies = [
    "cookiecutter==2.7.1",
    "ruff==0.16.3",        # use ruff check --fix, not ruff format.
    "pytest==9.1.1",
    "pytest-cov==7.1.0",
    "lefthook==2.1.12",
    "autopep8==2.3.2",     # autopep8 is better in whitespace formatting.
]

[project.scripts]
"cc-tmpl.py" = "cc_tmpl_py:main"

[build-system]
requires = [
    "uv_build>=0.12.5,<0.13.0",
]
build-backend = "uv_build"

[tool.autopep8]
max_line_length = 100

[tool.ruff]
line-length = 100
preview = true
extend-exclude = [
    "cc_modules",
]

[tool.ruff.lint]
extend-select = [
    "E",
    "W",
]
